SELECT WAITERS.LASTNAME,
       ORDERS_PCS
FROM WAITERS
INNER JOIN
  ( SELECT WAITER_ID,
           COUNT(ID) AS ORDERS_PCS
   FROM ORDERS
   GROUP BY WAITER_ID
   ORDER BY ORDERS_PCS DESC) AS RAITING ON WAITERS.ID = RAITING.WAITER_ID;

   SELECT CHEFS.LASTNAME,
          ORDERS_PCS
   FROM CHEFS
   INNER JOIN
     ( SELECT CHEF_ID,
              COUNT(ID) AS ORDERS_PCS
      FROM ORDERS
      GROUP BY CHEF_ID
      ORDER BY ORDERS_PCS DESC) AS RAITING ON CHEFS.ID = RAITING.CHEF_ID;
