SELECT * FROM MENUS;
UPDATE MENUS SET RESTAURANT_ID = 1 WHERE ID = 1;
UPDATE MENUS SET RESTAURANT_ID = 1 WHERE ID = 2;
UPDATE MENUS SET RESTAURANT_ID = 2 WHERE ID = 3;
UPDATE MENUS SET RESTAURANT_ID = 2 WHERE ID = 4;
UPDATE MENUS SET RESTAURANT_ID = 2 WHERE ID = 5;