default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: garmatniy
  password: dinamo26

development:
  <<: *default
  database: course_development_db

test:
  <<: *default
  database: course_test_db

production:
  <<: *default
  database: course_production_db
