# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47e2bd9c8d593f6a869246f148694e0b5883296d65f8995cca7d3d68fd832cd83237c15a4b1e9801ec62bfb545ee782d809b1560150958c65a8d96b6087332ba

test:
  secret_key_base: ac72ffc45fd260779a1c4144c3f27382b5ec8ac8c11a3343a24e7bdb64342427b04e79ef4d834b77cf02f1e0a556c13c4fc39472ce2e9ba5b92f1f087bef9859

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
